[TURSO]
url = "libsql://chat-d1124182034-hash.aws-ap-northeast-1.turso.io"
auth_token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjkwNjQ4MTksImlkIjoiMzAzYjQyZDItNmQzYi00MDMyLThmOGUtN2NhZTNmYjVmZTBlIiwicmlkIjoiNjI2MGY5MDEtMjM3Mi00MTRhLTliNzktYWM3ZjIxZTQxZmM2In0.aFM_I-6flRe8XDADxEqbt7_a-VhMWyPXm7xubg_I-AoNGY_9JpLX9T4oF_04aPwN0i1sMzj7H_aqHu9d0-DvAw"


[OLLAMA]
api_key = "e9269afda79d4fe1a0a087767fe96998.aI_qo8G2NvviDTDzKoGGnIEG"